### ISSUE TITLE
phpmyadmin on ubuntu 16.04

### ISSUE THREAD

**Issue by philippe-rero** [debops/ansible-phpmyadmin#3]
Hi, 

I installed without trouble debops.phpmyadmin on a debian 8.4 host. For another project I need a mariadb on ubuntu 16.04 host, it will be cool to have phpmyadmin too. But it depends on php5, is there a simple way to have it depends on the php available on ubuntu 16.04 (php7). Did I missed a configuration somewhere?

Best regards
Phil

**Comment by drybjed** [comment]
For now you could try and replace the debops.php5 dependency with debops.php, it should work with PHP7 out of the box. Keep in mind that the role is old and needs to be updated to support current DebOps environment (PHP7, MariaDB). I'll try to update the role as soon as I can, but not just yet.

**Comment by philippe-rero** [comment]
On Wed, 03 May 2017 06:56:58 -0700
Maciej Delmanowski <notifications@github.com> wrote:

> For now you could try and replace the debops.php5 dependency with
> debops.php, it should work with PHP7 out of the box. Keep in mind
> that the role is old and needs to be updated to support current
> DebOps environment (PHP7, MariaDB). I'll try to update the role as
> soon as I can, but not just yet.
> 

Thank you for the answer... the ubuntu case is no more a problem, for
other reasons it was not worth the pain it caused and we reverted to
using debian on this host too.

Best regards

PHiLippe 

-- 
Philippe Roud
RERO
Avenue de la Gare 45
1920 Martigny
Standard: +41 27 721 85 85
Direct: +41 27 721 85 91
